language: elixir
otp_release:
 - 18.3
 - 19.2
elixir:
 - 1.2.6
 - 1.3.4
 - 1.4.0
 - 1.5.1
matrix:
  include:
    - elixir: 1.5.1
      otp_release: 20.0
after_script:
  - MIX_ENV=dev mix deps.get
  - MIX_ENV=dev mix inch.report
branches:
  only:
    - master
