language: elixir
otp_release:
 - 20.3
elixir:
 - 1.4
 - 1.5
 - 1.6
cache:
  directories:
  - /home/travis/.mix
before_script:
 - mix dialyzer --plt
script:
 - mix test
 - mix dialyzer --halt-exit-status --no-check
after_script:
  - MIX_ENV=dev mix deps.get
  - MIX_ENV=dev mix inch.report
branches:
  only:
    - master
